openapi: 3.0.0
info:
  title: RAG Chatbot Chat API
  version: 1.0.0
  description: API for user interaction with the RAG chatbot.

servers:
  - url: /api/v1
    description: Base URL for the Chatbot API

paths:
  /chat/query:
    post:
      summary: Send a natural language query to the chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - query_text
                - session_id
              properties:
                user_id:
                  type: string
                  description: Unique identifier of the user.
                query_text:
                  type: string
                  description: The natural language question from the user.
                session_id:
                  type: string
                  description: Identifier for the current conversational session.
      responses:
        '200':
          description: Chatbot response successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response_id:
                    type: string
                    description: Unique ID for this chatbot response.
                  response_text:
                    type: string
                    description: The generated natural language answer.
                  session_id:
                    type: string
                    description: The conversational session ID.
        '400':
          description: Invalid request.
        '500':
          description: Internal server error.

  /chat/history:
    get:
      summary: Retrieve conversational history for a user/session
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
          required: true
          description: Unique identifier of the user.
        - in: query
          name: session_id
          schema:
            type: string
          required: false
          description: Optional session ID to filter history for a specific conversation.
      responses:
        '200':
          description: Conversational history retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: [user, bot]
                    text:
                      type: string
                    timestamp:
                      type: string
                      format: date-time
                    response_id:
                      type: string
                      description: (Optional) Only for bot responses.
        '400':
          description: Invalid parameters.
        '401':
          description: Unauthorized.

  /chat/sources/{response_id}:
    get:
      summary: Get source documents for a specific chatbot response
      parameters:
        - in: path
          name: response_id
          schema:
            type: string
          required: true
          description: Unique ID of the chatbot response.
      responses:
        '200':
          description: Source documents retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    document_id:
                      type: string
                    title:
                      type: string
                    excerpt:
                      type: string
                      description: Relevant snippet from the document.
                    url:
                      type: string
                      format: uri
                      description: Link back to the original document.
        '404':
          description: Response ID not found.

  /chat/feedback:
    post:
      summary: Submit feedback on a chatbot response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - response_id
                - feedback_type
              properties:
                response_id:
                  type: string
                  description: Unique ID of the chatbot response being rated.
                feedback_type:
                  type: string
                  enum: [positive, negative, irrelevant, inaccurate]
                  description: Type of feedback.
                comment:
                  type: string
                  nullable: true
                  description: Optional detailed comment.
      responses:
        '202':
          description: Feedback accepted.
        '400':
          description: Invalid request.
